### ISSUE TITLE
[REQUEST] v0.0.8-1 Activity Diary Previous Items Entered Highlighter

### ISSUE THREAD

**Issue by andy475uk** [VersCreativeUK/FACETS#86]
**Is your feature request related to a problem? If so, please describe.**
Difficult to see if entries have been entered previously in activity diary when you scroll back through dates or to current day.

**Describe the feature you would like**
Is there anyway to show visually if activities are present on a particular day when scrolling through the calendar - might not be possible?

**Priority**
Not essential feature

**Comment by andy475uk** [comment]
ps david - don't worry about looking at any of these issues/requests until after you get back - just going through some testing this morning (01/07 am). Thanks Andy :-)

**Comment by davcpas1234** [comment]
The plugin that we're using on android has the ability to add dots to dates example (far right):

![image](https://user-images.githubusercontent.com/3764587/60596864-c01e0880-9da1-11e9-94dd-b163bc306350.png)

marking as low priority as will need to work out a efficient way of calculating this

**Comment by andy475uk** [comment]
I like the idea of dots (blue  example) but we can check with everybody at a future project meeting and then see if there's time to implement before the end of the project

**Comment by davcpas1234** [comment]
After initial investigations, this is not possible to achieve. In order to add the "indicator dots" this call needs to be performed when the calendar view is created. However as we lookup activity entries asynchronously this prevents us from calling the method `addEvents()` on the calendar view.

`addEvents()` is part of the builder class and has not been implemented outside of this.
